export default [
    {
        id: 1,
        user_id: 1,
        title: 'My address 1',
        country: 'Россия',
        country_code: 'RU',
        index: '',
        region: 'Московская область',
        district: 'городской округ Солнечногорск',
        locality: 'Солнечногорск',
        locality2: '',
        street: 'улица Баранова',
        building: '2',
        room: '',
        corpus: '',
        floor: '',
        premise: '',
        coords: '56.182992, 36.978403',
        map_zoom: 15,
        text: 'Московская область, Солнечногорск, улица Баранова, 2',
        comment: `Venenatis convallis porta. Sagittis commodo platea Vivamus facilisi`
    },

    {
        id: 2,
        user_id: 1,
        title: 'My address 2',
        country: 'Россия',
        country_code: 'RU',
        index: '',
        region: 'Московская область"',
        district: 'городской округ Солнечногорск',
        locality: 'посёлок Смирновка',
        locality2: 'квартал Солнечный',
        street: '',
        building: '1',
        room: '',
        corpus: '',
        floor: '',
        premise: '',
        coords: '56.222991, 36.941015',
        map_zoom: 15,
        text: 'Московская область, городской округ Солнечногорск, посёлок Смирновка, квартал Солнечный, 1',
        comment: ``
    },

    {
        id: 3,
        user_id: 1,
        title: 'My address 3',
        country: 'Россия',
        country_code: 'RU',
        index: '',
        region: 'Московская область"',
        district: 'городской округ Солнечногорск',
        locality: 'село Алабушево',
        locality2: '',
        street: 'улица Калинина',
        building: '40',
        room: '',
        corpus: '',
        floor: '',
        premise: '',
        coords: '56.005143, 37.135509',
        map_zoom: 15,
        text: 'Московская область, городской округ Солнечногорск, село Алабушево, улица Калинина, 40',
        comment: `Venenatis convallis porta. Sagittis commodo platea Vivamus facilisi`
    },
];
